# Generated by Django 5.2.4 on 2026-04-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_complaint_reply_alter_maintenancerequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.apartment'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
